import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { getClientScript } from './client-script.js';

export interface PickrOptions {
  /** Port for the local dev server. Default: 37799 */
  port?: number;
  /** Project root for writing .yumyum_pickr.json. Default: process.cwd() */
  projectRoot?: string;
}

export interface ElementSelection {
  tag: string;
  id: string | null;
  classes: string[];
  selector: string;
  html: string;
  innerText: string;
  url: string;
  timestamp: number;
}

let _server: http.Server | null = null;
let _selection: ElementSelection | null = null;
let _projectRoot = process.cwd();
let _port = 37799;

export function getCurrentSelection(): ElementSelection | null {
  return _selection;
}

export async function startServer(options: PickrOptions = {}): Promise<void> {
  if (_server) return; // already running

  _port = options.port ?? 37799;
  _projectRoot = options.projectRoot ?? process.cwd();

  return new Promise((resolve) => {
    _server = http.createServer(handleRequest);

    _server.on('error', (err: NodeJS.ErrnoException) => {
      if (err.code === 'EADDRINUSE') {
        // Another instance is already running — that's fine
        _server = null;
      } else {
        console.error('[yumyum_pickr] Server error:', err.message);
      }
      resolve();
    });

    _server.listen(_port, '127.0.0.1', () => {
      console.log(`\n[yumyum_pickr] 🎯 Dev server running on http://localhost:${_port}`);
      console.log(`[yumyum_pickr]    Click the 🎯 button in your browser, or press Alt+P\n`);
      setupIdeConfigs();
      resolve();
    });
  });
}

export function stopServer(): void {
  _server?.close();
  _server = null;
}

/* ── Request handler ────────────────────────────────────────────── */

function handleRequest(req: http.IncomingMessage, res: http.ServerResponse): void {
  // CORS — allow browser to call us from any localhost port
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Serve the picker client script
  if (req.method === 'GET' && req.url === '/pickr.js') {
    res.writeHead(200, {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'no-store',
    });
    res.end(getClientScript(_port));
    return;
  }

  // Health check
  if (req.method === 'GET' && req.url === '/ping') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, version: '0.1.0' }));
    return;
  }

  // Return last selection (used by MCP server)
  if (req.method === 'GET' && req.url === '/current') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(_selection));
    return;
  }

  // Receive element selection from browser
  if (req.method === 'POST' && req.url === '/select') {
    let body = '';
    req.on('data', (chunk) => { body += chunk; });
    req.on('end', () => {
      try {
        _selection = JSON.parse(body) as ElementSelection;
        persistSelection(_selection);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      } catch {
        res.writeHead(400);
        res.end('Bad request');
      }
    });
    return;
  }

  res.writeHead(404);
  res.end();
}

/* ── Persist selection ──────────────────────────────────────────── */

function persistSelection(sel: ElementSelection): void {
  const outputPath = path.join(_projectRoot, '.yumyum_pickr.json');
  const data = {
    ...sel,
    _instructions: [
      'This file is generated by yumyum_pickr.',
      'In your AI chat, reference it with @.yumyum_pickr.json',
      'Or use the MCP tool: get_selected_element',
    ],
  };

  try {
    fs.writeFileSync(outputPath, JSON.stringify(data, null, 2), 'utf-8');
    console.log(`[yumyum_pickr] ✓ Captured: ${sel.selector} — ${sel.url}`);
  } catch (err) {
    console.error('[yumyum_pickr] Could not write .yumyum_pickr.json:', err);
  }
}

/* ── Auto-configure IDE MCP settings ───────────────────────────── */

function setupIdeConfigs(): void {
  setupCursorMcp();
  setupVscodeMcp();
}

function setupCursorMcp(): void {
  const dir = path.join(_projectRoot, '.cursor');
  const configPath = path.join(dir, 'mcp.json');

  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    let config: Record<string, unknown> = {};
    if (fs.existsSync(configPath)) {
      config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    }

    const servers = (config.mcpServers as Record<string, unknown>) ?? {};
    if (servers['yumyum_pickr']) return; // already configured

    config.mcpServers = {
      ...servers,
      yumyum_pickr: {
        command: 'npx',
        args: ['yumyum_pickr', 'mcp'],
        description: 'yumyum_pickr — visual element picker for AI chat context',
      },
    };

    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');
    console.log('[yumyum_pickr] ✓ Cursor MCP config written to .cursor/mcp.json');
    console.log('[yumyum_pickr]   Restart Cursor to enable get_selected_element tool');
  } catch {
    // Non-fatal — user can configure manually
  }
}

function setupVscodeMcp(): void {
  const dir = path.join(_projectRoot, '.vscode');
  const configPath = path.join(dir, 'mcp.json');

  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    let config: Record<string, unknown> = {};
    if (fs.existsSync(configPath)) {
      config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    }

    const servers = (config.servers as Record<string, unknown>) ?? {};
    if (servers['yumyum_pickr']) return;

    config.servers = {
      ...servers,
      yumyum_pickr: {
        type: 'stdio',
        command: 'npx',
        args: ['yumyum_pickr', 'mcp'],
      },
    };

    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8');
    console.log('[yumyum_pickr] ✓ VSCode MCP config written to .vscode/mcp.json');
  } catch {
    // Non-fatal
  }
}
